### ISSUE TITLE
Generating a figure with multiple logos in a matplotlib axes grid

### ISSUE THREAD

**Issue by adamklie** [betteridiot/seqlogo#13]
I'd like to be able to generate a single figure in a notebook which contains multiple logos organized in a grid (and save it in one image file). For instance, I generate 12 PWMs and I'd like to visualize them all in a single figure arranged as a 3x4 grid. Is this something that can be done? Ideally I'd like to be able to manipulate this figure using matplotlib as well.

Right now I use the `seqlogo.seqlogo` function to read in a `seqlogo.core.CompletePm` and generate a logo that is returned as an `IPython.core.display.Image object`. I'm not sure if there is a way to go from a set of these objects to what I'm looking for or if I need to change something in the way I am using seqlogo. Here is an example of what I currently do:

```python
print(pfm)  # the starting PFM generated from a set of sequences
         A      C      G       T
0    671.0  504.0  571.0  1793.0
1   1963.0  539.0  471.0   566.0
2   1378.0  557.0  562.0  1042.0
3   1979.0  493.0  487.0   580.0
4   1111.0  550.0  526.0  1345.0
5   1619.0  600.0  569.0   741.0
6    933.0  877.0  800.0   902.0
7   1160.0  733.0  674.0   935.0
8   1068.0  730.0  684.0  1001.0
9   1098.0  734.0  701.0   936.0
10  1057.0  748.0  703.0   946.0
11  1063.0  748.0  700.0   923.0
12  1026.0  719.0  721.0   952.0

cpm = seqlogo.CompletePm(pfm=pfm)  # call I make to generate cpm
logo = seqlogo.seqlogo(cpm, ic_scale=True, format="png")  # what I do to generate the logo
display(logo)  # how I usually display in a notebook
```
![image](https://user-images.githubusercontent.com/23622847/184935982-d502a801-a4b0-4363-82d2-2cd037e63808.png)

Is there a way to stack these objects into a matplotlib axes grid or do I need to return a different object from the `seqlogo.seqlogo` function? Is what I'm thinking about possible with here?

**Comment by betteridiot** [comment]
Apparently I wasn't receiving email notifications for new issues on this repo. I have no idea why, but nevertheless.

This can't really work because `seqlogo` is a wrapper for WebLogo. WebLogo produces plots that are directly written to PNG, PDF, etc. There is no intermediate object that plays nice with `matplotlib`, `seaborn`, etc.

Consider using [Logomaker](https://academic.oup.com/bioinformatics/article/36/7/2272/5671693), which is a more robust sequence motiff library. This is mainly because `seqlogo` was written specifically for classroom demonstration and introduction to sequence motiffs.
