### ISSUE TITLE
Matrix conversion and creation does not work when using ambiguous DNA sequences

### ISSUE THREAD

**Issue by eloilit** [betteridiot/seqlogo#8]
**Describe the bug**
The library doesn't work with ambiguous DNA sequences. There are lots of internal parts that seem to omit the supplied alphabet_type parameter, which causes it to default to DNA. 

**To Reproduce**
` A = seqlogo.Pfm(np.random.randint(0,10,size=(8,16)),alphabet_type="ambig DNA")`

This returns :
`A
           A          C          G          T
0  14.083333  22.250000  16.750000  19.916667
1  28.250000  21.416667  22.583333  30.750000
2  17.500000  10.500000   8.166667  16.833333
3  17.833333  14.500000  19.500000  18.166667
4  12.166667  10.666667  21.833333   8.333333
5  14.666667  18.500000  17.333333  20.500000
6  21.833333  17.500000  19.000000  14.666667
7  14.500000  18.333333  15.333333  19.833333`

**Expected behavior**
Matrix with ambiguous DNA frequencies instead of DNA frequencies

**Desktop (please complete the following information):**
 - OS: Linux version 5.4.0-37-generic (buildd@lcy01-amd64-001) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)) #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020

 - Python Version 3.7.6
 - NumPy Version 1.18.1
 - Pandas Version 1.0.3
 - matplotlib Version 3.1.3

**Comment by betteridiot** [comment]
This commit (f265220fbad4962e13a061311b86cee5170c937b) should fix the bug you've experienced. The issue was some of the internal conversion functions were not passing all of the arguments to the next. An example of the workflow can be seen below:

```python
import numpy as np
import pandas as pd
import seqlogo as sl

# Classic (for sanity)
# Setting seed for demonstration purposes
>>> np.random.seed(42)

# Making a fake PWM
random_ppm = np.random.dirichlet(np.ones(4), size=6)
ppm = sl.Ppm(random_ppm)
sl.seqlogo(
    ppm, 
    ic_scale = False, 
    format = 'svg', 
    size = 'medium'
)
```
![image](https://user-images.githubusercontent.com/25447319/85420473-3c74a300-b541-11ea-8940-1ec5effe9d47.png)

```python
# Now checking ambiguous letter support
dat = np.random.randint(0, 36 ,size = (8, 16))
A = sl.Pfm(
    dat,
    alphabet_type="ambig DNA",
    # Have to set a background if the alphabet is a different length than the canonical sequence
    background = .0625                  
)
sl.seqlogo(
    sl.Cpm(
        pfm = A, 
        alphabet_type='ambig DNA', 
        background = 0.0625
    ),
    ic_scale = False, 
    format = 'svg', 
    size = 'medium'
)
```
![image](https://user-images.githubusercontent.com/25447319/85420990-e6542f80-b541-11ea-9539-a256c2fcf4e1.png)

I have to push an update to PyPI before it will be updated on `bioconda`. Either install from this or wait for that update.
